# Generated by Django 6.0.3 on 2026-03-08 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cloudinary_url', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('ocr_vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('ocr_date', models.DateField(blank=True, null=True)),
                ('ocr_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ocr_raw_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending OCR'), ('reviewed', 'OCR Reviewed'), ('saved', 'Transaction Saved')], default='pending', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
